// <auto-generated />
namespace FPTBookStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class sevenRun : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sevenRun));
        
        string IMigrationMetadata.Id
        {
            get { return "202202191638449_sevenRun"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
